import { StyleSheet } from "react-native";

export const dishCardStyles = StyleSheet.create({
    dishCard: {
        flexDirection: "row",
        height: 120,
        borderRadius: 16,
        marginBottom: 16,
        borderWidth: 1,
        overflow: "hidden",
        position: "relative",
        shadowColor: "#000",
        shadowOffset: { width: 0, height: 3 },
        shadowOpacity: 0.1,
        shadowRadius: 6,
        elevation: 4,
    },
    dishContent: {
        flex: 1,
        flexDirection: "row",
    },
    blurredContent: {
        opacity: 0.3,
    },
    imageSection: {
        width: 120,
        height: "100%",
    },
    dishImage: {
        width: "100%",
        height: "100%",
    },
    contentSection: {
        flex: 1,
        padding: 16,
        justifyContent: "space-between",
    },
    nameRow: {
        marginBottom: 8,
    },
    dishName: {
        fontSize: 18,
        fontWeight: "700",
        lineHeight: 22,
    },
    calorieRow: {
        marginBottom: 8,
        flexDirection: "row",
        alignItems: "center",
        justifyContent: "space-between",
    },
    calorieChip: {
        flexDirection: "row",
        alignItems: "center",
        paddingHorizontal: 8,
        paddingVertical: 4,
        borderRadius: 12,
        backgroundColor: "rgba(52, 152, 219, 0.15)",
    },
    calorieText: {
        fontSize: 12,
        fontWeight: "600",
        marginLeft: 4,
    },
    costContainer: {
        flexDirection: "row",
        alignItems: "center",
        backgroundColor: "#F8F9FA",
        borderRadius: 10,
        paddingHorizontal: 8,
        paddingVertical: 4,
    },
    outdoorCost: {
        flexDirection: "row",
        alignItems: "center",
    },
    outdoorCostText: {
        fontSize: 11,
        fontWeight: "700",
        color: "#FF6B6B",
        marginLeft: 3,
    },
    costSeparator: {
        width: 1,
        height: 12,
        backgroundColor: "#E0E0E0",
        marginHorizontal: 8,
    },
    homeCost: {
        flexDirection: "row",
        alignItems: "center",
    },
    homeCostText: {
        fontSize: 11,
        fontWeight: "700",
        color: "#4ECDC4",
        marginLeft: 3,
    },
    metadataRow: {
        marginBottom: 8,
    },
    metadataContainer: {
        flexDirection: "row",
        alignItems: "center",
    },
    cultureChip: {
        paddingHorizontal: 8,
        paddingVertical: 3,
        borderRadius: 8,
        marginRight: 6,
    },
    cultureText: {
        color: "#FFFFFF",
        fontSize: 10,
        fontWeight: "600",
        textTransform: "uppercase",
        letterSpacing: 0.3,
    },
    metadataText: {
        fontSize: 10,
        fontWeight: "500",
        textTransform: "uppercase",
        letterSpacing: 0.5,
    },
    actionsContainer: {
        position: "absolute",
        top: 12,
        left: 12,
        right: 12,
        flexDirection: "row",
        justifyContent: "space-between",
        zIndex: 10,
    },
    actionButton: {
        width: 32,
        height: 32,
        borderRadius: 16,
        alignItems: "center",
        justifyContent: "center",
        shadowColor: "#000",
        shadowOffset: { width: 0, height: 2 },
        shadowOpacity: 0.15,
        shadowRadius: 4,
        elevation: 3,
    },
});